### ISSUE TITLE
Bowtie vs BWA

### ISSUE THREAD

**Issue by sivico26** [uio-bmi/NucBreak#5]
Hi! I just discovered this promising tool when I found its latest [article](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-3414-0).

I have a question regarding the mapping tool used: Is there a specific reason to use Bowtie2 over BWA? And if there is not, would be possible to use BWA somehow?

I see in the paper that option `--rna` is used when mapping with Bowtie2, is that the reason? If an RNA mapping tool is needed, wouldn't be better to use Hisat2 or magicblast? 

Thanks in advance!
Sivico

**Comment by kseniakh** [comment]
Hi Sivico,

Yes, there were reasons to use Bowtie2 and not BWA. First, Bowtie2 allows to output all possible alignments for each read. Second, it has quite effective soft clipping approach (is set up by --ma 1) . Unfortunately, it was not possible to use BWA the same way. 

In the paper, it is written '-ma' , but not '-rna'. The tool doesn't work with RNA sequencing data.  But I see that it may be misleading. 

Ksenia

**Comment by sivico26** [comment]
Thank you very much for the clarification. Really helpful!
